### PR TITLE
Try add nvidia integration based on DistroBox code

### PR DESCRIPTION
**Pull request by Boria138**

### CODE REVIEW

**Comment by VHSgunzo** [comment]
@Boria138 

I've thought about this point before, it seems to me the best way is to cut out everything related to the `list` from this tool:
    [libnvidia-container](https://github.com/NVIDIA/libnvidia-container)
    [libnvidia-container-tools](https://aur.archlinux.org/packages/libnvidia-container-tools)
```
nvidia-container-cli list --binaries --libraries --compat32
```
And compile it statically.

And there is also a problem with systems that do not have 32-bit versions of nvidia libraries, and the main message of the runimage container is that "you do not need to install anything into the system", so I was in no hurry to implement bind Nvidia libraries from the system, and flatpak does the same in this regard. Perhaps for such cases it is possible to make separate images with only 32-bit versions of nvidia libraries and download/create it only if there are none in the system

and as far as I understood in PR, the possibility of the container working in a packed (RO) form is excluded, this is not quite correct. this functionality should work both packed and unpacked (or in overlay mode) container

**Comment by Boria138** [comment]
> @Boria138 
> 
> I've thought about this point before, it seems to me the best way is to cut out everything related to the `list` from this tool:
>     [libnvidia-container](https://github.com/NVIDIA/libnvidia-container)
>     [libnvidia-container-tools](https://aur.archlinux.org/packages/libnvidia-container-tools)
> ```
> nvidia-container-cli list --binaries --libraries --compat32
> ```
> And compile it statically.
> 
> And there is also a problem with systems that do not have 32-bit versions of nvidia libraries, and the main message of the runimage container is that "you do not need to install anything into the system", so I was in no hurry to implement bind Nvidia libraries from the system, and flatpak does the same in this regard. Perhaps for such cases it is possible to make separate images with only 32-bit versions of nvidia libraries and download/create it only if there are none in the system
> 
> and as far as I understood in PR, the possibility of the container working in a packed (RO) form is excluded, this is not quite correct. this functionality should work both packed and unpacked (or in overlay mode) container

I think downloading 32 bit libraries in the absence of them sounds good, I decided to make this pr because I thought that downloading what is already in the system is not very expedient, but to download what is not already logical.

**Comment by Boria138** [comment]
@VHSgunzo 
I made a temporary forced download of drivers until I figure out how to correctly rewrite the download and mounting of drivers separately 64-bit and separately 32, I also have a small question about the code in the code I do 

I made a temporary forced download of drivers until I figure out how to correctly rewrite the download and mounting of drivers separately 64-bit and separately 32, I also have a small question about the code in the code I do 

```sh
NVIDIA_FILES="$(find /etc/ /usr/ \
		-path "/usr/lib/i386-linux-gnu/*" -prune -o \.
		-path "/usr/lib/x86_64-linux-gnu/*" -prune -o \.
		-path "/usr/lib32/*" -prune -o \
		-path "/usr/lib64/*" -prune -o \.
		-iname "*nvidia*" -not -type d -print 2> /dev/null || :)"

for nvidia_file in ${NVIDIA_FILES}; do
		NVIDIA_DRIVER_BIND+=("--ro-bind-try" "${nvidia_file}" "${RUNROOTFS}/${nvidia_file}"))
	done
```
In the distrobox itself, where I got the code from, this is done in the following way

```sh
	NVIDIA_FILES="$(find /run/host/etc/ /run/host/usr/ \
		-path "/run/host/usr/lib/i386-linux-gnu/*" -prune -o \
		-path "/run/host/usr/lib/x86_64-linux-gnu/*" -prune -o \.
		-path "/run/host/usr/lib32/*" -prune -o \
		-path "/run/host/usr/lib64/*" -prune -o \.
		-iname "*nvidia*" -not -type d -print 2> /dev/null || :)"

	for nvidia_file in ${NVIDIA_FILES}; do
		dest_file="$(printf "%s" "${nvidia_file}" | sed 's|/run/host|||g')")"

		mount_bind "${nvidia_file}" "${dest_file}" ro
	done
```

Question do I need ${RUNROOTFS} or can I just specify $nvidia_file ?

**Comment by VHSgunzo** [comment]
> Question do I need ${RUNROOTFS} or can I just specify $nvidia_file ?

bind arguments take first the path on the host side, then the native path that should be inside the container
i.e. there is no need to use ${RUNROOTFS}

But I also want to note that these `find` conditions work slowly and bring out a lot of unnecessary "garbage", which makes no sense to bind to the container

And on debian-like systems, searching in /usr/lib/x86_64-linux-gnu or /usr/lib/i386-linux-gnu and trying to bind them to the base runimage container, which is based on rootfs from Arch Linux, will cause problems, because libraries are stored there in other places if you do not configure the paths search for ldconfig inside the container. This is also one of the reasons why I was in no hurry to make this bind of libraries from the system.

**Comment by VHSgunzo** [comment]
Also about downloading only 32-bit nvidia libraries... as far as I know, nvidia does not supply them separately, which means that I will either need to make images with them for all driver versions, or users will still download a full-fledged RUN file that already has these libraries and the image will be assembled on their systems

**Comment by VHSgunzo** [comment]
This again leads to the idea that it is easier and better not to rely on user systems, which by the way may have problems even with 64-bit versions of Nvidia libraries, but to provide them with a ready-made image with all the necessary libraries at once

**Comment by Boria138** [comment]
> And on debian-like systems, searching in /usr/lib/x86_64-linux-gnu or /usr/lib/i386-linux-gnu and trying to bind them to the base runimage container, which is based on rootfs from Arch Linux, will cause problems, because libraries are stored there in other places if you do not configure the paths search for ldconfig inside the container. This is also one of the reasons why I was in no hurry to make this bind of libraries from the system.

Probably fixed

**Comment by Boria138** [comment]
> But I also want to note that these `find` conditions work slowly and bring out a lot of unnecessary "garbage", which makes no sense to bind to the container

And if you search for libraries not through find, but through ldconfig, there is something like this ?

```sh
ldconfig -p | awk '/nvidia/{print $4}' && ldconfig -p | awk '/libcuda/{print $4}'
```

**Comment by Boria138** [comment]
@VHSgunzo How about this ?

```sh
share_nvidia_driver(){
	# NVIDIA driver integration. This is straight from https://github.com/89luca89/distrobox/blob/main/distrobox-init#L1478,

	# First we find all non-lib files we need, this includes
	#	- binaries
	#	- egl files
	#	- icd files
	#	Excluding here the libs, we will treat them later specifically
	NVIDIA_FILES="$(find /usr/share/vulkan/ /usr/share/egl/ /usr/bin/ \
		-iname "*nvidia*" -not -type d -print 2> /dev/null || :)"
	for nvidia_file in ${NVIDIA_FILES}; do
		NVIDIA_DRIVER_BIND+=("--ro-bind-try"  "${nvidia_file}" "${nvidia_file}")
	done

        # Then we find all directories with nvidia in the name and just mount them
	NVIDIA_DIRS="$(find /usr/lib -iname "*nvidia*" -type d 2> /dev/null || :)"
	for nvidia_dir in ${NVIDIA_DIRS}; do
		if printf "%s" "${nvidia_dir}" | grep -Eq "x86_64-linux-gnu|i386-linux-gnu"; then
			# Remove origin so we plug our own
			dest_dir=$(printf "%s" "${nvidia_dir}" |
				sed "s|/usr/lib/x86_64-linux-gnu/|/usr/lib64/|g" |
				sed "s|/usr/lib/i386-linux-gnu/|/usr/lib32/|g")
		else
			dest_dir="${nvidia_dir}"
		fi

		NVIDIA_DRIVER_BIND+=("--ro-bind-try"  "${nvidia_dir}" "${dest_dir}")
	done	
	
	# Then we find all the ".so" libraries, they are searched separately
	# because we need to extract the relative path to mount them in the
	# correct path based on the guest's setup
	#
	# /usr/lib64 is common in Arch or RPM based distros, while /usr/lib/x86_64-linux-gnu is
	# common on Debian derivatives, so we need to adapt between the two nomenclatures.
	NVIDIA_LIBS="$(ldconfig -p | awk '/nvidia/{print $4}' \
	&& ldconfig -p | awk '/libcuda/{print $4}'  \
	&& ldconfig -p | awk '/libnvoptix/{print $4}' \
	&& ldconfig -p | awk '/libnvcuvid/{print $4}' 2> /dev/null || :)"
	for nvidia_lib in ${NVIDIA_LIBS}; do
		if printf "%s" "$nvidia_lib" | grep -Eq "x86_64-linux-gnu|i386-linux-gnu"; then
			# Remove origin so we plug our own
			dest_dir=$(printf "%s" "$nvidia_lib" |
				sed "s|/usr/lib/x86_64-linux-gnu/|/usr/lib64/|g" |
				sed "s|/usr/lib/i386-linux-gnu/|/usr/lib32/|g")
		else
			dest_dir="${nvidia_lib}"
		fi

		# If file exists, just continue
		# this may happen for directories like /usr/lib/nvidia/xorg/foo.so
		# where the directory is already bind mounted (ro) and we don't need
		# to mount further files in it.
		if [ -e "$dest_dir" ]; then
			continue
		fi

		type="file"
		if [ -L "${nvidia_lib}" ]; then
			type="link"
		fi

		if [ "${type}" = "link" ]; then
			mkdir -p "$(dirname "${dest_dir}")"
			cp -d "${nvidia_lib}" "${dest_dir}"
			continue
		fi
		NVIDIA_DRIVER_BIND+=("--ro-bind-try"  "${nvidia_lib}" "${dest_dir}")
	done

	# Refresh ldconfig cache, also detect if there are empty files remaining
	# and clean them.
	# This could happen when upgrading drivers and changing versions.
	empty_libs="$(ldconfig 2>&1 | grep -Eo "File.*is empty" | cut -d' ' -f2)"
	if [ -n "${empty_libs}" ]; then
		# shellcheck disable=SC2086
		find ${empty_libs} -delete 2> /dev/null || :
		find /usr/ -empty -iname "*nvidia*" -delete 2> /dev/null || :
	fi
}
```

**Comment by Boria138** [comment]
> Also about downloading only 32-bit nvidia libraries... as far as I know, nvidia does not supply them separately, which means that I will either need to make images with them for all driver versions, or users will still download a full-fledged RUN file that already has these libraries and the image will be assembled on their systems

I thought to make arguments for function get_nvidia_driver_image by type 32bit and 64bit, the full-fledged run driver is downloaded, but it is unpacked already the necessary architecture and both if there are no arguments

**Comment by VHSgunzo** [comment]
@Boria138 

I'm thinking of making a list of files (as in the image of the nvidia driver for the runimage container) to search in the system, then form a directory from the found files with the same structure as in the unpacked image and use it to bind to the container so that each time the container is started, you don't have to search again.
And if something from this list of files is not found in the system, then download the image (or NVIDIA.run file and create an image already in the system)
This approach will also work for a packed (RO) container

**Comment by VHSgunzo** [comment]
> > Also about downloading only 32-bit nvidia libraries... as far as I know, nvidia does not supply them separately, which means that I will either need to make images with them for all driver versions, or users will still download a full-fledged RUN file that already has these libraries and the image will be assembled on their systems
> 
> I thought to make arguments for function get_nvidia_driver_image by type 32bit and 64bit, the full-fledged run driver is downloaded, but it is unpacked already the necessary architecture and both if there are no arguments

I'm talking about not downloading the 64-bit part at all, but only the 32-bit part, and Nvidia does not have this

**Comment by VHSgunzo** [comment]
@Boria138 
I wrote a [script](https://gist.github.com/VHSgunzo/6ecf1bd1d8108ff62525961e356cae4a) to create an image from the system libraries, no checks are done there, and the image is created "as is"
This is not very reliable, because some libraries may not be in the system (including 64-bit ones), but Nvidia can change various libraries in the driver from version to version and you cannot rely on their name and number.

The script creates a driver image for the container in order to then bind it inside in the usual way. Because this is the only way to ensure work even for a packed container (RO)

The container also understands the unpacked driver image. I.e., lines 133-135 can be excluded. Or you can reduce the compression ratio to 1, in which case the image is created in ~4 seconds in my system from the system libraries.

**Comment by VHSgunzo** [comment]
Maybe I'll integrate it into Run.sh soon with checks for the presence of 32-bit libraries in the system and this will be as a separate option, and I also need to run tests on various distributions with the nvidia driver.

**Comment by VHSgunzo** [comment]
By default, I still prefer to leave the option with downloading the image or with automatically assembling it in the system from the RUN file of the nvidia driver

**Comment by Boria138** [comment]
> Maybe I'll integrate it into Run.sh soon with checks for the presence of 32-bit libraries in the system and this will be as a separate option, and I also need to run tests on various distributions with the nvidia driver.

If you are going to integrate your script, then I guess there is no point in this pr anymore

**Comment by VHSgunzo** [comment]
> > Maybe I'll integrate it into Run.sh soon with checks for the presence of 32-bit libraries in the system and this will be as a separate option, and I also need to run tests on various distributions with the nvidia driver.
> 
> If you are going to integrate your script, then I guess there is no point in this pr anymore

if you want, you can help with the tests of building the driver image using this script on different distributions

**Pull request closed without merging**
